package com.diego.iatrainig.dto;

import com.diego.iatrainig.domain.AthleteSnapshot;
import com.diego.iatrainig.domain.TrainingDay;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.List;

/**
 * Body of POST /api/v1/planes.
 * Receives the JSON generated by Gemini and validated before persisting.
 */
public record WeeklyPlanRequest(

        @NotBlank
        String userId,

        @Min(1)
        int weekNumber,

        @Min(1)
        int mesocycle,

        @NotBlank
        String phase,

        @NotBlank
        String objective,

        @NotNull
        LocalDate startDate,

        @NotNull
        LocalDate endDate,

        @NotNull @Valid
        AthleteSnapshot athlete,

        @NotEmpty @Valid
        List<TrainingDay> trainingDays
) {}
