package com.diego.iatrainig.domain;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Weekly training plan generated by Gemini. Immutable after creation.
 */
@Data
@Document(collection = "plan_semana")
@CompoundIndexes({
        @CompoundIndex(name = "mesocycle_week", def = "{'mesocycle': 1, 'week_number': 1}")
})
public class WeeklyPlan {

    @Id
    private String id;

    @Indexed
    private String userId;

    @Indexed
    private int weekNumber;

    private int mesocycle;
    private String phase;
    private String objective;

    @Indexed
    private LocalDate startDate;

    private LocalDate endDate;
    private LocalDateTime loadedAt;
    private AthleteSnapshot athlete;
    private List<TrainingDay> trainingDays;
}
